### ISSUE TITLE
What's wrong with my connected code

### ISSUE THREAD

**Issue by flyliufu** [dji-sdk/RoboMaster-SDK#26]
``` Python
    robomaster.config.LOCAL_IP_STR = "192.168.1.253"
    robomaster.config.DEFAULT_CONN_PROTO = "udp"
    ep_robot = robot.Robot()
    ep_robot.initialize(conn_type="ap", sn="3JKDH5S0018877")

    ep_version = ep_robot.get_version()
    print("Robot Version: {0}".format(ep_version))

    ep_robot.close()
```
run with error is :
``` text
ERROR conn.py:268 SdkConnection: RECV TimeOut!
ERROR robot.py:1169 Robot: Connection Failed, Please Check Hareware Connections!!! conn_type ap, host ('192.168.1.253', 10302), target ('192.168.2.1', 20020).
ERROR robot.py:1132 Robot: Connection Create Failed.
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。
Exception ignored in: <function Robot.__del__ at 0x0000017744351700>
Exception ignored in: <function Client.__del__ at 0x000001773D561940>
AttributeError: 'NoneType' object has no attribute 'is_alive'
```
my local ip is 192.168.1.253 , s1 ip is auto set 
anyone can help me ? thx

**Comment by brunoga** [comment]
I did not look too closely at your code but the problem you are having does not seem to be because the code is wrong. You mention the S1 but the S1 is not supported by this SDK, only the EP (although I did get this to also work with the S1 through a hack).

Also, there is a bug in the provided python SDK when you try to use TCP or UDP directly (this is the last error message you see). Use infrastructure mode (sta) and everything gets easier.

**Comment by flyliufu** [comment]
> I did not look too closely at your code but the problem you are having does not seem to be because the code is wrong. You mention the S1 but the S1 is not supported by this SDK, only the EP (although I did get this to also work with the S1 through a hack).
> 
> Also, there is a bug in the provided python SDK when you try to use TCP or UDP directly (this is the last error message you see). Use infrastructure mode (sta) and everything gets easier.
